### ISSUE TITLE
No longer able to drag Konsole terminal tabs

### ISSUE THREAD

**Issue by atowler84** [blue-systems/netrunner-16-issues#4]
I'm no longer able to rearrange the terminal tabs in Konsole by clicking and dragging them.

**Comment by davidedmundson** [comment]
Yeah, it's not Netrunner specific. Track upstream here: https://bugs.kde.org/show_bug.cgi?id=348057

**Comment by davidedmundson** [comment]
Fixed.
In review. Will probably be there in next release (so a month from now)

**Comment by davidedmundson** [comment]
Done.
